### PR TITLE
Sync code snippet with selected icon

### LINKED ISSUE #12: Update snippet based on selection
### Problem

Currently the snippet is hardcoded to color icons at 24px. This gives you a nice start, but it would be more helpful to give you a snippet with the exact style and size you're looking for

### Proposal

Make icons selectable and update the snippet based on the selection

### Prior Art (Optional)

FontAwesome: https://fontawesome.com/icons/objects-align-top?s=duotone&f=classic

### PR DESCRIPTION
**Pull request by Antolius**
Resolves #12 

I wrapped icons in toggle buttons, tracked the selected one and updated example code snippet accordingly. This also fixes an issue with incorrect snippet for symbolic only icons or those without size 24px, for which the static snippet doesn't work.

Example of using it:

[dynamic-snippet-showcase.webm](https://user-images.githubusercontent.com/5374391/203643843-3fedc582-7ca3-42c9-af0d-1254ffcbc980.webm)

### CODE REVIEW

**Comment by Antolius** [comment]
Sorry for the linting errors, I'll fix them tonight.

**Comment by zeebok** [comment]
The code itself seems fine, but I do wonder about the styling. Is there a way to easily have the buttons be a uniform width? For example when there is only one icon in a group, it taking up the full width doesn't feel nice, to me anyway. Maybe someone from @elementary/ux can weigh in.

**Comment by zeebok** [comment]
This is definitely better and am okay with it. I think before any final thumbs-up for merging it should get the ok from @elementary/ux or at least @danirabbit since she had the original vision for the app.

**Review by danirabbit — CHANGES_REQUESTED** [review]
Probably what would be a cleaner way to do this is use a Gtk.FlowBox. This would give us a lot of things for free like setting a single selection mode, the ability to make sure children are homogeneous, and signals for when a child is selected

**Comment by danirabbit** [comment]
@Antolius Can you give a look to https://github.com/elementary/iconbrowser/pull/32?

**Comment by Antolius** [comment]
Ah, yes, using Gtk.FlowBox makes much more sense than the shenanigans I was up to here. I'll close this PR in favor of #32

**Pull request closed without merging**
